name: Release Production
on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

      - name: Build and push Docker image
        run: |
          docker build -f packages/api/Dockerfile -t registry.heroku.com/$HEROKU_APP_NAME/web .
          docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Deploy to Heroku
        run: |
          heroku container:release web --app $HEROKU_APP_NAME
